config/routes.rb
Commoncore::Application.routes.draw do
  resources :forms

  resources :rcategories
  resources :assessments

  resources :attachments do
     get :upload, on: :member
     get :take, on: :member
   end
  
  devise_for :students
  resources :students

  resources :xaquestions do
    put :select_aquestions, on: :member
    put :unselect_aquestions, on: :member
    put :add, on: :member
    collection { post :sort }
  end

  resources :xquestions do
    put :select_questions, on: :member
    put :unselect_questions, on: :member
    put :add, on: :member
    collection { post :sort }
  end

  resources :xvocabs do
    put :select_vocabs, on: :member
    put :unselect_vocabs, on: :member
    put :add, on: :member
    collection { post :sort }
  end

  resources :xlinks do
    put :select_links, on: :member
    put :unselect_links, on: :member
    put :add, on: :member
    collection { post :sort }
  end

  resources :lesson_resources

  devise_for :users, :path => '', :path_names => { :sign_up => "register", :sign_in => 'login', :sign_out => 'logout', :account_update => "update_account" }

  resources :headers

  resources :plans

  resources :select_aquestions

  resources :aquestions

  resources :resources do
    get :upload, on: :member
    get :gallery, on: :member
  end

  resources :sources

  resources :select_links

  resources :select_strategies

  resources :select_vocabs

  resources :select_skills

  resources :select_questions

  resources :districts

  resources :lessonplans

  resources :books do 
    put :select_books, on: :member
    put :unselect_books, on: :member
    collection do   
      get :show_sources
      get :show2
      get :hide
      get :grade
      get :show_list
    end
  end

  resources :links

  resources :vocabs

  resources :questions

  resources :cskills
  resources :skills
  resources :caquestions
  scope "selects/:select_id" do
    resources :lesson_steps do
      get :hide

    end
  end

  root to: 'static_pages#home'
  
  resources :selects do
    resources :google_forms, :on => :member
    resources :mailers
    resources :assessments
    resources :cquestions
    resources :cskills
    resources :cvocabs
    resources :cstrategies
    resources :clinks
    resources :caquestions
    resources :lesson_resources
    member do
      get 'post_questions'
      put 'post_qs'
      get 'post_aquestions'
      put 'post_aqs'
      get 'post_skills'
      put 'post_ss'
      get 'post_links'
      put 'post_ls'
      get 'post_vocabs'
      put 'post_vs'
      get 'post_script'
      get 'publish'
      get 'fork'
    end
  end
    resources :users do
    resources :students
  end

  
  
  resources :standards do
    collection do
      get :hide
    end
  end

  match 'lessons',  to: 'selects#index'
  match 'lesson',  to: 'selects#edit'

  match 'gradek',  to: 'selects#grade0'
  match 'grade1',  to: 'selects#grade1'
  match 'grade2',  to: 'selects#grade2'
  match 'grade3',  to: 'selects#grade3'
  match 'grade4',  to: 'selects#grade4'
  match 'grade5',  to: 'selects#grade5'
  match 'grade6',  to: 'selects#grade6'
  match 'grade7',  to: 'selects#grade7'
  match 'grade8',  to: 'selects#grade8'

  
  match '/home',    to: 'static_pages#home'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'

end

app/models/xaquestion.rb
class Xaquestion < ActiveRecord::Base
	acts_as_list
attr_accessible :content, :standard_id, :select_id
  belongs_to :standard
  belongs_to :select
end

app/controllers/xaquestions_controller.rb
class XaquestionsController < ApplicationController
    def create
      @select = Select.find(params[:select_id])
      @standard = Standard.find(params[:standard_id])
      @saquestions = SelectAquestion.where(:select_id => @select.id)
      @xaquestion = Xaquestion.new
      @xaquestion.standard_id = @standard.id
      @xaquestion.select_id = @select.id


      respond_to do |format|
        if @xaquestion.save
            @selectq = SelectAquestion.new
            @selectq.select_id = @select.id
            @selectq.xaquestion_id = @xaquestion.id
            @selectq.save
            format.js

        else
          render :action => 'new'
        end
        end
      end
  
      def new
        @select = Select.find(params[:select_id])
        @standard = Standard.find(params[:standard_id])
        @saquestions = SelectAquestion.where(:select_id => @select.id).last
        @xaquestion = Xaquestion.new
        respond_to do |format|
          format.js
        end
      end
  
    def update
    @xaquestion = Xaquestion.find(params[:id])

    respond_to do |format|
      if @xaquestion.update_attributes(params[:xaquestion])
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @xaquestion.errors, status: :unprocessable_entity }
      end
    end
  end
    
    def destroy
      @xaquestion = Xaquestion.find(params[:id])
      @select = Select.find(params[:select_id])
      @xaquestion.destroy
      
      redirect_to edit_select_path(@select)
    end
    
    def edit
    @select = Select.find(params[:select_id])
    @standards = @select.standards.all
    @ids = @standards.map{|standard| standard.id}
    @xaquestion = Xaquestion.new
    end
    
    def show
      @select = Select.find(params[:select_id])
      @xaquestion = Xaquestion.find(params[:id])
    end
    
    def index
    end

    def select_aquestions
    @xaquestion = Xaquestion.find(params[:id])
    @select = Select.find(params[:select_id])
      @selectq = @select.select_aquestions.new
      @selectq.select_id = @select.id
      @selectq.xaquestion_id = @xaquestion.id

      if @selectq.save
      respond_to do |format|
        format.js
      end
      end
end

    def unselect_aquestions
    @xaquestion = Xaquestion.find(params[:id])
    @select = Select.find(params[:select_id])
      @selectq = SelectAquestion.where(:xaquestion_id => @xaquestion.id).where(:select_id => @select.id).last
      @selectq.delete
      respond_to :js
    end

    def add
    @xaquestion = Xaquestion.find(params[:id])
    @select = Select.find(params[:select_id])
    
    @select.notes = @select.notes + "<br/>" +  @xaquestion.content
    @select.save
      respond_to :js
    end
 def sort
  params[:xlink].each_with_index do |id, index|
    Xlink.update_all({position: index+1}, {id: id})
  end
  render nothing: true
  end
end

app/helpers/xaquestions_helper.rb
module XaquestionsHelper
end

app/views/xaquestions/_add.html.erb
 <%= simple_form_for(@select, remote: true) do |f| %>
            <%= f.input :notes, label: false, :input_html => { class: 'wysihtml5', style: 'width:100%; height:400' } %>
            <% end %>

app/views/xaquestions/_form.html.erb
<%= simple_form_for(@xaquestion) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/xaquestions/_new.html.erb
<%= simple_form_for(@xaquestion, :remote => true) do |f| %>
<div class="row animated fadeIn" id="resources">

<div class="col-md-1">
<div id="xaquestion_<%= @xaquestion.id %>">

    <% if @saquestions.map{|a| a.xaquestion_id}.include? @xaquestion.id %>
      <%= link_to "",  unselect_aquestions_xaquestion_path(@xaquestion, :select_id => @select.id), method: :put, remote: :true, :class => "btn btn-link glyphicon glyphicon-check" %>
      <% else %>
      <%= link_to "",  select_aquestions_xaquestion_path(@xaquestion, :select_id => @select.id), method: :put, remote: :true, :class => "btn btn-link glyphicon glyphicon-unchecked" %>
      <% end %>
    </div>
    </div>
    <div class="col-md-1"></div>
<div class="col-md-9">

  <fieldset>
<div class="form-inputs">
  <%= f.input :content, label: false, as: :text, :input_html => {:rows => 2} %>



</div>
</fieldset>

  </div>
  <div class="col-md-1"></div>
</div>
<% end %>

app/views/xaquestions/_select_aquestion.html.erb
<div class="animated pulse">
<%= link_to "",  unselect_aquestions_xaquestion_path(xaquestion, :select_id => @select.id), method: :put, remote: :true, :class => "btn btn-link glyphicon glyphicon-check" %>
</div>

app/views/xaquestions/_unselect_aquestion.html.erb
<div class="animated wobble">
<%= link_to "",  select_aquestions_xaquestion_path(xaquestion, :select_id => @select.id), method: :put, remote: :true, :class => "btn btn-link glyphicon glyphicon-unchecked" %>
</div>

app/views/xaquestions/add.js.erb
$('#notes1').html('<%= escape_javascript(render(:partial => 'add', :locals => {:select => @select})) %>')

app/views/xaquestions/create.js.erb
$(newaquestion_<%= @standard.standard_id %>).append('<%= escape_javascript(render(:partial => 'new', :locals => {:standard => @standard, :select => @select, :xaquestion => @xaquestion})) %>')

app/views/xaquestions/edit.html.erb
<h1>Editing xaquestion</h1>

<%= render 'form' %>

<%= link_to 'Show', @xaquestion %> |
<%= link_to 'Back', xaquestions_path %>

app/views/xaquestions/index.html.erb
<h1>Listing xaquestions</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @xaquestions.each do |xaquestion| %>
  <tr>
    <td><%= link_to 'Show', xaquestion %></td>
    <td><%= link_to 'Edit', edit_xaquestion_path(xaquestion) %></td>
    <td><%= link_to 'Destroy', xaquestion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Xaquestion', new_xaquestion_path %>

app/views/xaquestions/new.html.erb
<h1>New xaquestion</h1>

<%= render 'form' %>

<%= link_to 'Back', xaquestions_path %>

app/views/xaquestions/select_aquestions.js.erb
$(xaquestion1_<%= @xaquestion.id %>).html('<%= escape_javascript(render(:partial => 'select_aquestion', :locals => {:xaquestion => @xaquestion})) %>')

app/views/xaquestions/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_xaquestion_path(@xaquestion) %> |
<%= link_to 'Back', xaquestions_path %>

app/views/xaquestions/unselect_aquestions.js.erb
$(xaquestion1_<%= @xaquestion.id %>).html('<%= escape_javascript(render(:partial => 'unselect_aquestion', :locals => {:xaquestion => @xaquestion})) %>')