config/routes.rb
Commoncore::Application.routes.draw do
  resources :forms

  resources :rcategories
  resources :assessments

  resources :attachments do
     get :upload, on: :member
     get :take, on: :member
   end
  
  devise_for :students
  resources :students

  resources :xaquestions do
    put :select_aquestions, on: :member
    put :unselect_aquestions, on: :member
    put :add, on: :member
    collection { post :sort }
  end

  resources :xquestions do
    put :select_questions, on: :member
    put :unselect_questions, on: :member
    put :add, on: :member
    collection { post :sort }
  end

  resources :xvocabs do
    put :select_vocabs, on: :member
    put :unselect_vocabs, on: :member
    put :add, on: :member
    collection { post :sort }
  end

  resources :xlinks do
    put :select_links, on: :member
    put :unselect_links, on: :member
    put :add, on: :member
    collection { post :sort }
  end

  resources :lesson_resources

  devise_for :users, :path => '', :path_names => { :sign_up => "register", :sign_in => 'login', :sign_out => 'logout', :account_update => "update_account" }

  resources :headers

  resources :plans

  resources :select_aquestions

  resources :aquestions

  resources :resources do
    get :upload, on: :member
    get :gallery, on: :member
  end

  resources :sources

  resources :select_links

  resources :select_strategies

  resources :select_vocabs

  resources :select_skills

  resources :select_questions

  resources :districts

  resources :lessonplans

  resources :books do 
    put :select_books, on: :member
    put :unselect_books, on: :member
    collection do   
      get :show_sources
      get :show2
      get :hide
      get :grade
      get :show_list
    end
  end

  resources :links

  resources :vocabs

  resources :questions

  resources :cskills
  resources :skills
  resources :caquestions
  scope "selects/:select_id" do
    resources :lesson_steps do
      get :hide

    end
  end

  root to: 'static_pages#home'
  
  resources :selects do
    resources :google_forms, :on => :member
    resources :mailers
    resources :assessments
    resources :cquestions
    resources :cskills
    resources :cvocabs
    resources :cstrategies
    resources :clinks
    resources :caquestions
    resources :lesson_resources
    member do
      get 'post_questions'
      put 'post_qs'
      get 'post_aquestions'
      put 'post_aqs'
      get 'post_skills'
      put 'post_ss'
      get 'post_links'
      put 'post_ls'
      get 'post_vocabs'
      put 'post_vs'
      get 'post_script'
      get 'publish'
      get 'fork'
    end
  end
    resources :users do
    resources :students
  end

  
  
  resources :standards do
    collection do
      get :hide
    end
  end

  match 'lessons',  to: 'selects#index'
  match 'lesson',  to: 'selects#edit'

  match 'gradek',  to: 'selects#grade0'
  match 'grade1',  to: 'selects#grade1'
  match 'grade2',  to: 'selects#grade2'
  match 'grade3',  to: 'selects#grade3'
  match 'grade4',  to: 'selects#grade4'
  match 'grade5',  to: 'selects#grade5'
  match 'grade6',  to: 'selects#grade6'
  match 'grade7',  to: 'selects#grade7'
  match 'grade8',  to: 'selects#grade8'

  
  match '/home',    to: 'static_pages#home'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'

end

app/models/xquestion.rb
class Xquestion < ActiveRecord::Base
	acts_as_list
  attr_accessible :content, :standard_id, :select_id, :bold, :highlight, :italic
  belongs_to :standard
  belongs_to :select
end

app/controllers/xquestions_controller.rb
class XquestionsController < ApplicationController
    def create
      @select = Select.find(params[:select_id])
      @standard = Standard.find(params[:standard_id])
      @squestions = SelectQuestion.where(:select_id => @select.id)
      @xquestion = Xquestion.new
      @xquestion.standard_id = @standard.id
      @xquestion.select_id = @select.id


      respond_to do |format|
        if @xquestion.save
            @selectq = SelectQuestion.new
            @selectq.select_id = @select.id
            @selectq.xquestion_id = @xquestion.id
            @selectq.save
            format.js

        else
          render :action => 'new'
        end
        end
      end
  
      def new
        @select = Select.find(params[:select_id])
        @standard = Standard.find(params[:standard_id])
        @squestions = SelectQuestion.where(:select_id => @select.id).last
        @xquestion = Xquestion.new
        respond_to do |format|
          format.js
        end
      end
  
    def update
      @xquestion = Xquestion.find(params[:id])
      
        if @xquestion.update_attributes(params[:xquestion])
          respond_to :js
        else
          render :action => 'edit'
      end
    end
    
    def destroy
      @xquestion = Xquestion.find(params[:id])
      @select = Select.find(params[:select_id])
      @xquestion.destroy
      
      redirect_to edit_select_path(@select)
    end
    
    def edit
    @select = Select.find(params[:select_id])
    @standards = @select.standards.all
    @ids = @standards.map{|standard| standard.id}
    @xquestion = Xquestion.new
    end
    
    def show
      @select = Select.find(params[:select_id])
      @xquestion = Xquestion.find(params[:id])
    end
    
    def index
    end

    def select_questions
    @xquestion = Xquestion.find(params[:id])
    @select = Select.find(params[:select_id])
      @selectq = @select.select_questions.new
      @selectq.select_id = @select.id
      @selectq.xquestion_id = @xquestion.id

      if @selectq.save
      respond_to do |format|
        format.js
      end
      end
end

    def unselect_questions
    @xquestion = Xquestion.find(params[:id])
    @select = Select.find(params[:select_id])
      @selectq = SelectQuestion.where(:xquestion_id => @xquestion.id).where(:select_id => @select.id).last
      @selectq.delete
      respond_to :js
    end

    def add
    @xquestion = Xquestion.find(params[:id])
    @select = Select.find(params[:select_id])
    
    @select.notes = @select.notes + "<br/>" +  @xquestion.content
    @select.save
      respond_to :js
    end

  def sort
  params[:xquestion].each_with_index do |id, index|
    Xquestion.update_all({position: index+1}, {id: id})
  end
  render nothing: true
  end
end

app/helpers/xquestions_helper.rb
module XquestionsHelper
end

app/views/xquestions/_add.html.erb
 <%= simple_form_for(@select, remote: true) do |f| %>
            <%= f.input :notes, label: false, :input_html => { class: 'wysihtml5', style: 'width:100%; height:400' } %>
            <% end %>

app/views/xquestions/_form.html.erb
<%= simple_form_for(@xquestion) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/xquestions/_new.html.erb
<%= simple_form_for(@xquestion, remote: true, class: "xquestion") do |parent_form| %>
<div class="row animated fadeIn" id="resources">

<div class="col-md-1">
<div id="xquestion_<%= @xquestion.id %>">

<% if @squestions.map{|a| a.xquestion_id}.include? @xquestion.id %>
      <%= link_to "",  unselect_questions_xquestion_path(@xquestion, :select_id => @select.id), method: :put, remote: :true, :class => "btn btn-link glyphicon glyphicon-check" %>
      <% else %>
      <%= link_to "",  select_questions_xvocab_path(@xquestion, :select_id => @select.id), method: :put, remote: :true, :class => "btn btn-link glyphicon glyphicon-unchecked" %>
      <% end %>
    </div>
    </div>
    <div class="col-md-1"></div>
<div class="col-md-9">

  <fieldset>
<div class="form-inputs">
  <%= parent_form.input :content, label: false, as: :text, :input_html => {:rows => 2} %>

</div>
</fieldset>

  </div>
  <div class="col-md-1"></div>
</div>
<% end %>

app/views/xquestions/_select_question.html.erb
<div class="animated pulse">
<%= link_to "",  unselect_questions_xquestion_path(xquestion, :select_id => @select.id), method: :put, remote: :true, :class => "btn btn-link glyphicon glyphicon-check" %>
</div>

app/views/xquestions/_unselect_question.html.erb
<div class="animated wobble">
<%= link_to "",  select_questions_xquestion_path(xquestion, :select_id => @select.id), method: :put, remote: :true, :class => "btn btn-link glyphicon glyphicon-unchecked" %>
</div>

app/views/xquestions/add.js.erb
$('#notes1').html('<%= escape_javascript(render(:partial => 'add', :locals => {:select => @select})) %>')

app/views/xquestions/create.js.erb
$(xquestion_standard_<%= @standard.standard_id %>).replaceWith('<%= escape_javascript(render(:partial => 'lesson_steps/xquestions', :locals => {:standard => @standard })) %>')

app/views/xquestions/edit.html.erb
<h1>Editing xquestion</h1>

<%= render 'form' %>

<%= link_to 'Show', @xquestion %> |
<%= link_to 'Back', xquestions_path %>

app/views/xquestions/index.html.erb
<h1>Listing xquestions</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @xquestions.each do |xquestion| %>
  <tr>
    <td><%= link_to 'Show', xquestion %></td>
    <td><%= link_to 'Edit', edit_xquestion_path(xquestion) %></td>
    <td><%= link_to 'Destroy', xquestion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Xquestion', new_xquestion_path %>

app/views/xquestions/new.html.erb
<h1>New xquestion</h1>

<%= render 'form' %>

<%= link_to 'Back', xquestions_path %>

app/views/xquestions/new.js.erb
$(newquestion_<%= @standard.standard_id %>).append('<%= escape_javascript(render(:partial => 'new', :locals => {:standard => @standard, :select => @select, :xquestion => @xquestion})) %>')

app/views/xquestions/select_questions.js.erb
$(xquestion1_<%= @xquestion.id %>).html('<%= escape_javascript(render(:partial => 'select_question', :locals => {:xquestion => @xquestion})) %>')

app/views/xquestions/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_xquestion_path(@xquestion) %> |
<%= link_to 'Back', xquestions_path %>

app/views/xquestions/unselect_questions.js.erb
$(xquestion1_<%= @xquestion.id %>).html('<%= escape_javascript(render(:partial => 'unselect_question', :locals => {:xquestion => @xquestion})) %>')