config/routes.rb
Commoncore::Application.routes.draw do
  resources :forms

  resources :rcategories
  resources :assessments

  resources :attachments do
     get :upload, on: :member
     get :take, on: :member
   end
  
  devise_for :students
  resources :students

  resources :xaquestions do
    put :select_aquestions, on: :member
    put :unselect_aquestions, on: :member
    put :add, on: :member
    collection { post :sort }
  end

  resources :xquestions do
    put :select_questions, on: :member
    put :unselect_questions, on: :member
    put :add, on: :member
    collection { post :sort }
  end

  resources :xvocabs do
    put :select_vocabs, on: :member
    put :unselect_vocabs, on: :member
    put :add, on: :member
    collection { post :sort }
  end

  resources :xlinks do
    put :select_links, on: :member
    put :unselect_links, on: :member
    put :add, on: :member
    collection { post :sort }
  end

  resources :lesson_resources

  devise_for :users, :path => '', :path_names => { :sign_up => "register", :sign_in => 'login', :sign_out => 'logout', :account_update => "update_account" }

  resources :headers

  resources :plans

  resources :select_aquestions

  resources :aquestions

  resources :resources do
    get :upload, on: :member
    get :gallery, on: :member
  end

  resources :sources

  resources :select_links

  resources :select_strategies

  resources :select_vocabs

  resources :select_skills

  resources :select_questions

  resources :districts

  resources :lessonplans

  resources :books do 
    put :select_books, on: :member
    put :unselect_books, on: :member
    collection do   
      get :show_sources
      get :show2
      get :hide
      get :grade
      get :show_list
    end
  end

  resources :links

  resources :vocabs

  resources :questions

  resources :cskills
  resources :skills
  resources :caquestions
  scope "selects/:select_id" do
    resources :lesson_steps do
      get :hide

    end
  end

  root to: 'static_pages#home'
  
  resources :selects do
    resources :google_forms, :on => :member
    resources :mailers
    resources :assessments
    resources :cquestions
    resources :cskills
    resources :cvocabs
    resources :cstrategies
    resources :clinks
    resources :caquestions
    resources :lesson_resources
    member do
      get 'post_questions'
      put 'post_qs'
      get 'post_aquestions'
      put 'post_aqs'
      get 'post_skills'
      put 'post_ss'
      get 'post_links'
      put 'post_ls'
      get 'post_vocabs'
      put 'post_vs'
      get 'post_script'
      get 'publish'
      get 'fork'
    end
  end
    resources :users do
    resources :students
  end

  
  
  resources :standards do
    collection do
      get :hide
    end
  end

  match 'lessons',  to: 'selects#index'
  match 'lesson',  to: 'selects#edit'

  match 'gradek',  to: 'selects#grade0'
  match 'grade1',  to: 'selects#grade1'
  match 'grade2',  to: 'selects#grade2'
  match 'grade3',  to: 'selects#grade3'
  match 'grade4',  to: 'selects#grade4'
  match 'grade5',  to: 'selects#grade5'
  match 'grade6',  to: 'selects#grade6'
  match 'grade7',  to: 'selects#grade7'
  match 'grade8',  to: 'selects#grade8'

  
  match '/home',    to: 'static_pages#home'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'

end

app/models/xlink.rb
class Xlink < ActiveRecord::Base
	acts_as_list
  attr_accessible :comment, :link, :standard_id, :select_id
  belongs_to :standard
  belongs_to :select
end

app/controllers/xlinks_controller.rb
class XlinksController < ApplicationController
  # GET /xlinks
  # GET /xlinks.json
  def index
    @xlinks = Xlink.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @xlinks }
    end
  end

  # GET /xlinks/1
  # GET /xlinks/1.json
  def show
    @xlink = Xlink.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @xlink }
    end
  end

  # GET /xlinks/new
  # GET /xlinks/new.json
  def new
    @xlink = Xlink.new

    respond_to do |format|
      format.js
    end
  end

  # GET /xlinks/1/edit
  def edit
    @xlink = Xlink.find(params[:id])
  end

  # POST /xlinks
  # POST /xlinks.json
  def create
      @select = Select.find(params[:select_id])
      @standard = Standard.find(params[:standard_id])
      @slinks = SelectLink.where(:select_id => @select.id)
      @xlink = Xlink.new
      @xlink.standard_id = @standard.id
      @xlink.select_id = @select.id


      respond_to do |format|
        if @xlink.save
            @selectl = SelectLink.new
            @selectl.select_id = @select.id
            @selectl.xlink_id = @xlink.id
            @selectl.save
            format.js

        else
          render :action => 'new'
        end
        end
      end

  # PUT /xlinks/1
  # PUT /xlinks/1.json
  def update
    @xlink = Xlink.find(params[:id])

    respond_to do |format|
      if @xlink.update_attributes(params[:xlink])
        format.html { redirect_to @xlink, notice: 'Xlink was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @xlink.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /xlinks/1
  # DELETE /xlinks/1.json
  def destroy
    @xlink = Xlink.find(params[:id])
    @xlink.destroy

    respond_to do |format|
      format.html { redirect_to xlinks_url }
      format.json { head :no_content }
    end
  end

  def select_links
    @xlink = Xlink.find(params[:id])
    @select = Select.find(params[:select_id])
      @selectl = @select.select_links.new
      @selectl.select_id = @select.id
      @selectl.xlink_id = @xlink.id

      if @selectl.save
      respond_to do |format|
        format.js
      end
      end
end

    def unselect_links
    @xlink = Xlink.find(params[:id])
    @select = Select.find(params[:select_id])
      @selectl = SelectLink.where(:xlink_id => @xlink.id).where(:select_id => @select.id).last
      @selectl.delete
      respond_to :js
    end

    def add
    @xlink = Xlink.find(params[:id])
    @select = Select.find(params[:select_id])
    
    @select.notes = @select.notes + "<br/>" +  @xlink.comment + "<br/>" + @xlink.link
    @select.save
      respond_to :js
    end

  def sort
  params[:xlink].each_with_index do |id, index|
    Xlink.update_all({position: index+1}, {id: id})
  end
  render nothing: true
  end
end

app/helpers/xlinks_helper.rb
module XlinksHelper
end

app/views/xlinks/_add.html.erb
 <%= simple_form_for(@select, remote: true) do |f| %>
            <%= f.input :notes, label: false, :input_html => { class: 'wysihtml5', style: 'width:100%; height:400' } %>
            <% end %>

app/views/xlinks/_form.html.erb
<%= simple_form_for(@xlink) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/xlinks/_new.html.erb
<%= simple_form_for(@xlink, :remote => true) do |f| %>
<div class="row animated fadeIn" id="resources">

<div class="col-md-1">
<div id="xlink_<%= @xlink.id %>">

    <% if @slinks.map{|a| a.xlink_id}.include? @xlink.id %>
      <%= link_to "",  unselect_links_xlink_path(@xlink, :select_id => @select.id), method: :put, remote: :true, :class => "btn btn-link glyphicon glyphicon-check" %>
      <% else %>
      <%= link_to "",  select_links_xlink_path(@xlink, :select_id => @select.id), method: :put, remote: :true, :class => "btn btn-link glyphicon glyphicon-unchecked" %>
      <% end %>
    </div>
    </div>
   
<div class="col-md-10">

  <fieldset>
<div class="form-inputs">
<%= f.input :link, label: false, as: :text, :input_html => {:rows => 2}, label_method: "Resource:" %>
  <%= f.input :comment, label: false, as: :text, :input_html => {:rows => 2}, label_method: "Comment" %>



</div>
</fieldset>

  </div>
  <div class="col-md-1"></div>
</div>
<% end %>

app/views/xlinks/_select_link.html.erb
<div class="animated pulse">
<%= link_to "",  unselect_links_xlink_path(xlink, :select_id => @select.id), method: :put, remote: :true, :class => "btn btn-link glyphicon glyphicon-check" %>
</div>

app/views/xlinks/_unselect_link.html.erb
<div class="animated wobble">
<%= link_to "",  select_links_xlink_path(xlink, :select_id => @select.id), method: :put, remote: :true, :class => "btn btn-link glyphicon glyphicon-unchecked" %>
</div>

app/views/xlinks/add.js.erb
$('#notes1').html('<%= escape_javascript(render(:partial => 'add', :locals => {:select => @select})) %>')

app/views/xlinks/create.js.erb
$(newlink_<%= @standard.standard_id %>).append('<%= escape_javascript(render(:partial => 'new', :locals => {:standard => @standard, :select => @select, :xlink => @xlink})) %>')

app/views/xlinks/edit.html.erb
<h1>Editing xlink</h1>

<%= render 'form' %>

<%= link_to 'Show', @xlink %> |
<%= link_to 'Back', xlinks_path %>

app/views/xlinks/index.html.erb
<h1>Listing xlinks</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @xlinks.each do |xlink| %>
  <tr>
    <td><%= link_to 'Show', xlink %></td>
    <td><%= link_to 'Edit', edit_xlink_path(xlink) %></td>
    <td><%= link_to 'Destroy', xlink, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Xlink', new_xlink_path %>

app/views/xlinks/new.html.erb
<h1>New xlink</h1>

<%= render 'form' %>

<%= link_to 'Back', xlinks_path %>

app/views/xlinks/select_links.js.erb
$(xlink1_<%= @xlink.id %>).html('<%= escape_javascript(render(:partial => 'select_link', :locals => {:xlink => @xlink})) %>')

app/views/xlinks/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_xlink_path(@xlink) %> |
<%= link_to 'Back', xlinks_path %>

app/views/xlinks/unselect_links.js.erb
$(xlink1_<%= @xlink.id %>).html('<%= escape_javascript(render(:partial => 'unselect_link', :locals => {:xlink => @xlink})) %>')