config/routes.rb
Commoncore::Application.routes.draw do
  resources :forms

  resources :rcategories
  resources :assessments

  resources :attachments do
     get :upload, on: :member
     get :take, on: :member
   end
  
  devise_for :students
  resources :students

  resources :xaquestions do
    put :select_aquestions, on: :member
    put :unselect_aquestions, on: :member
    put :add, on: :member
    collection { post :sort }
  end

  resources :xquestions do
    put :select_questions, on: :member
    put :unselect_questions, on: :member
    put :add, on: :member
    collection { post :sort }
  end

  resources :xvocabs do
    put :select_vocabs, on: :member
    put :unselect_vocabs, on: :member
    put :add, on: :member
    collection { post :sort }
  end

  resources :xlinks do
    put :select_links, on: :member
    put :unselect_links, on: :member
    put :add, on: :member
    collection { post :sort }
  end

  resources :lesson_resources

  devise_for :users, :path => '', :path_names => { :sign_up => "register", :sign_in => 'login', :sign_out => 'logout', :account_update => "update_account" }

  resources :headers

  resources :plans

  resources :select_aquestions

  resources :aquestions

  resources :resources do
    get :upload, on: :member
    get :gallery, on: :member
  end

  resources :sources

  resources :select_links

  resources :select_strategies

  resources :select_vocabs

  resources :select_skills

  resources :select_questions

  resources :districts

  resources :lessonplans

  resources :books do 
    put :select_books, on: :member
    put :unselect_books, on: :member
    collection do   
      get :show_sources
      get :show2
      get :hide
      get :grade
      get :show_list
    end
  end

  resources :links

  resources :vocabs

  resources :questions

  resources :cskills
  resources :skills
  resources :caquestions
  scope "selects/:select_id" do
    resources :lesson_steps do
      get :hide

    end
  end

  root to: 'static_pages#home'
  
  resources :selects do
    resources :google_forms, :on => :member
    resources :mailers
    resources :assessments
    resources :cquestions
    resources :cskills
    resources :cvocabs
    resources :cstrategies
    resources :clinks
    resources :caquestions
    resources :lesson_resources
    member do
      get 'post_questions'
      put 'post_qs'
      get 'post_aquestions'
      put 'post_aqs'
      get 'post_skills'
      put 'post_ss'
      get 'post_links'
      put 'post_ls'
      get 'post_vocabs'
      put 'post_vs'
      get 'post_script'
      get 'publish'
      get 'fork'
    end
  end
    resources :users do
    resources :students
  end

  
  
  resources :standards do
    collection do
      get :hide
    end
  end

  match 'lessons',  to: 'selects#index'
  match 'lesson',  to: 'selects#edit'

  match 'gradek',  to: 'selects#grade0'
  match 'grade1',  to: 'selects#grade1'
  match 'grade2',  to: 'selects#grade2'
  match 'grade3',  to: 'selects#grade3'
  match 'grade4',  to: 'selects#grade4'
  match 'grade5',  to: 'selects#grade5'
  match 'grade6',  to: 'selects#grade6'
  match 'grade7',  to: 'selects#grade7'
  match 'grade8',  to: 'selects#grade8'

  
  match '/home',    to: 'static_pages#home'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'

end

app/models/grade.rb
class Grade < ActiveRecord::Base
  attr_accessible :number
  has_many :standards
  has_many :texts
  has_many :selects
  has_many :books
  has_many :book_grades
  has_many :books, through: :book_grades

  has_many :select_grades
  has_many :selects, through: :select_grades

  has_many :document_grades
  has_many :documents, through: :document_grades

  has_many :resource_grades
  has_many :resources, through: :resource_grades
end

app/views/resources/_form.html.erb
<%= simple_form_for(@resource) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  <%= f.input :title, input_html: {style: 'height:100px; width:100%'} %>
    <%= f.input :content, input_html: {style: 'height:100px; width:100%'} %>
    <%= f.association :rcategory %>
    <%= f.association :grades, as: :check_boxes, input_html: {:data => {:toggle => "checkbox"}} %>
    <%= f.input :filetype_id, label: 'What type of file is this?', collection: [ ['1', 'PDF' ], ['2', 'Doc'], ['3', 'Image/JPEG'] ], as: :radio_buttons, label_method: :last, value_method: :first, checked: @resource.filetype_id, item_wrapper_class: 'inline' , input_html: {:data => {:toggle => "radio"}}%>

	 <%= f.input :file %>  
  </div>
<br />
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<%= link_to "Make new category", new_rcategory_path %>
<br/>

app/views/resources/_resources.html.erb
<%= form_for(@attachment, remote: true) do |f| %>
<div class="modal-dialog modal-dialog-center"  id="resources">
    <div class="modal-content height" id="resources">
      <div class="modal-header" id="resources" align="right">
            <%= f.submit "Add Selected Resources to Your Lesson", class: "btn btn-primary wait" %>

        <h4 class="modal-title" id="myModalLabel"></h4>
      </div>
      <div class="modal-body" id="resources">
      <% @resources.each_slice(6) do |slice| %>
  <div class="gallery">
    <% slice.each do |resource| %>
    <%= check_box_tag "attachment[resource_ids][]", resource.id, @attachment.resource_ids.include?(resource.id) %>
    <% @url = "https://docs.google.com/file/d/" + "#{resource.google_url}" + "/preview" %>
<iframe width='200' height='300' frameborder='0' src='<%= @url %>' sandbox="allow-same-origin allow-scripts allow-popups"></iframe>

    <% end %>
  </div>
<% end %>
  
      <div class="form-actions">
      <div class="modal-footer">

      </div>   
      </div>   

    </div>
  </div>
</div>

<% end %>

<script>
$(".wait").on("click", function() {
  $('#myModal').modal('hide');
  setTimeout(function(){
    $('#myModal').modal('show');
  $("#modal-window").html("<%= escape_javascript(render partial: 'attachments/wait') %>"); 
}, 500);

});

</script>

app/views/resources/edit.html.erb
<h1>Editing resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/gallery.js.erb
$('#myModal').modal('hide');
  setTimeout(function(){
    $('#myModal').modal('show');
  $("#modal-window").html("<%= escape_javascript(render partial: 'resources/resources') %>"); 
}, 500);
  

app/views/resources/index.html.erb
<h1>Resources</h1>

<table>


<% @resources.each do |resource| %>
  <tr>
    <td><%= resource.title %></td></tr>
    <tr><td><%= resource.content %></td></tr>
   <tr> <td><%= simple_format(resource.media) %></td></tr>
  <tr>
    <td><%= link_to 'Show', resource %></td>

  </tr>
<% end %>
</table>

<br />
<% if current_user && current_user.admin? %>
Admin: 
<%= link_to 'New Resource', new_resource_path %>
<% end %>

app/views/resources/new.html.erb
<h1>New resource</h1>

<%= render 'form' %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= @resource.title %>
</p>
<iframe width='910' height='660' frameborder='0' src='<%= @id %>' sandbox="allow-same-origin allow-scripts allow-popups"></iframe>

<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>